name: Run API tests
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Build ENV
      run: mkdir ./Examples/Data/License/
    - name: Add total license
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'Aspose.Total.NET.lic'
        fileDir: './Examples/Data/License/'
        encodedString: ${{ secrets.API_LICENSE }}
    - name: Add words license
      uses: timheuer/base64-to-file@v1.2
      with:
        fileName: 'Aspose.Words.NET.lic'
        fileDir: './Examples/Data/License/'
        encodedString: ${{ secrets.API_WORDS_LICENSE }}
    - name: Restore dependencies
      run: dotnet restore ./Examples/ApiExamples/ApiExamples/ApiExamples.csproj
    - name: Build
      run: dotnet build --no-restore ./Examples/ApiExamples/ApiExamples/ApiExamples.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults" ./Examples/ApiExamples/ApiExamples/ApiExamples.csproj
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
